// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    accounts,
    feeds,
    feedInputs,
    servers,
    feedSourceCache,
    readPostCache,
    filterLists,
    profiles,
    stars,
    miscCache,
    drafts,
    tags,
    userTags,
  ];
  late final Shape0 accounts = Shape0(
    source: i0.VersionedTable(
      entityName: 'accounts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(handle)'],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 feeds = Shape1(
    source: i0.VersionedTable(
      entityName: 'feeds',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(name)'],
      columns: [_column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 feedInputs = Shape2(
    source: i0.VersionedTable(
      entityName: 'feed_inputs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(name)'],
      columns: [_column_5, _column_4, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 servers = Shape3(
    source: i0.VersionedTable(
      entityName: 'servers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(name)'],
      columns: [_column_4, _column_7, _column_8],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 feedSourceCache = Shape4(
    source: i0.VersionedTable(
      entityName: 'feed_source_cache',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(name, server)'],
      columns: [_column_9, _column_10, _column_11, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 readPostCache = Shape5(
    source: i0.VersionedTable(
      entityName: 'read_post_cache',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(account, post_type, post_id)'],
      columns: [_column_12, _column_13, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 filterLists = Shape6(
    source: i0.VersionedTable(
      entityName: 'filter_lists',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(name)'],
      columns: [_column_4, _column_15, _column_16, _column_17, _column_18],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 profiles = Shape7(
    source: i0.VersionedTable(
      entityName: 'profiles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(name)'],
      columns: [
        _column_4,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
        _column_65,
        _column_66,
        _column_67,
        _column_68,
        _column_69,
        _column_70,
        _column_71,
        _column_72,
        _column_73,
        _column_74,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 stars = Shape8(
    source: i0.VersionedTable(
      entityName: 'stars',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_75, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 miscCache = Shape9(
    source: i0.VersionedTable(
      entityName: 'misc_cache',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_76,
        _column_77,
        _column_78,
        _column_79,
        _column_80,
        _column_81,
        _column_82,
        _column_83,
        _column_84,
        _column_85,
        _column_86,
        _column_87,
        _column_88,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 drafts = Shape10(
    source: i0.VersionedTable(
      entityName: 'drafts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_75, _column_89, _column_90, _column_91],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 tags = Shape11(
    source: i0.VersionedTable(
      entityName: 'tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_75, _column_92, _column_93, _column_94],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 userTags = Shape12(
    source: i0.VersionedTable(
      entityName: 'user_tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user, tag_id)'],
      columns: [_column_95, _column_96],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get handle =>
      columnsByName['handle']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get oauth =>
      columnsByName['oauth']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get jwt =>
      columnsByName['jwt']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isPushRegistered =>
      columnsByName['is_push_registered']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'handle',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'oauth',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'jwt',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_push_registered',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (is_push_registered IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get feed =>
      columnsByName['feed']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'feed',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES feeds(name)ON UPDATE CASCADE ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get software =>
      columnsByName['software']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get oauthIdentifier =>
      columnsByName['oauth_identifier']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'software',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'oauth_identifier',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get server =>
      columnsByName['server']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sourceId =>
      columnsByName['source_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_9(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'name',
  aliasedName,
  false,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'NOT NULL REFERENCES feed_inputs(name)ON UPDATE CASCADE ON DELETE CASCADE',
);
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'server',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES servers(name)',
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'source_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get account =>
      columnsByName['account']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get postType =>
      columnsByName['post_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get postId =>
      columnsByName['post_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'account',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES accounts(handle)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'post_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'post_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get phrases =>
      columnsByName['phrases']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get matchMode =>
      columnsByName['match_mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get caseSensitive =>
      columnsByName['case_sensitive']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get showWithWarning =>
      columnsByName['show_with_warning']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'phrases',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'match_mode',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'case_sensitive',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (case_sensitive IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'show_with_warning',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (show_with_warning IN (0, 1))',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get autoSwitchAccount =>
      columnsByName['auto_switch_account']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get defaultCreateLanguage =>
      columnsByName['default_create_language']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get disableTabSwiping =>
      columnsByName['disable_tab_swiping']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get askBeforeUnsubscribing =>
      columnsByName['ask_before_unsubscribing']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get askBeforeDeleting =>
      columnsByName['ask_before_deleting']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get autoPlayVideos =>
      columnsByName['auto_play_videos']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get hapticFeedback =>
      columnsByName['haptic_feedback']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get autoTranslate =>
      columnsByName['auto_translate']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get markThreadsReadOnScroll =>
      columnsByName['mark_threads_read_on_scroll']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get markMicroblogsReadOnScroll =>
      columnsByName['mark_microblogs_read_on_scroll']!
          as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get animationSpeed =>
      columnsByName['animation_speed']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get inlineReplies =>
      columnsByName['inline_replies']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get showCrossPostComments =>
      columnsByName['show_cross_post_comments']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get markCrossPostsAsRead =>
      columnsByName['mark_cross_posts_as_read']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get defaultImageStore =>
      columnsByName['default_image_store']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get appLanguage =>
      columnsByName['app_language']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get themeMode =>
      columnsByName['theme_mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get colorScheme =>
      columnsByName['color_scheme']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get enableTrueBlack =>
      columnsByName['enable_true_black']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get compactMode =>
      columnsByName['compact_mode']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get hideActionButtons =>
      columnsByName['hide_action_buttons']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get hideFeedUIOnScroll =>
      columnsByName['hide_feed_u_i_on_scroll']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get globalTextScale =>
      columnsByName['global_text_scale']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get alwaysShowInstance =>
      columnsByName['always_show_instance']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get coverMediaMarkedSensitive =>
      columnsByName['cover_media_marked_sensitive']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fullImageSizeThreads =>
      columnsByName['full_image_size_threads']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fullImageSizeMicroblogs =>
      columnsByName['full_image_size_microblogs']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get showPostsCards =>
      columnsByName['show_posts_cards']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get postComponentOrder =>
      columnsByName['post_component_order']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get dividerThickness =>
      columnsByName['divider_thickness']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get hideEmojiReactions =>
      columnsByName['hide_emoji_reactions']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get feedViewOrder =>
      columnsByName['feed_view_order']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedSourceOrder =>
      columnsByName['feed_source_order']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedSortOrder =>
      columnsByName['feed_sort_order']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedDefaultThreadsSort =>
      columnsByName['feed_default_threads_sort']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedDefaultMicroblogSort =>
      columnsByName['feed_default_microblog_sort']!
          as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedDefaultCombinedSort =>
      columnsByName['feed_default_combined_sort']!
          as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedDefaultExploreSort =>
      columnsByName['feed_default_explore_sort']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedDefaultCommentSort =>
      columnsByName['feed_default_comment_sort']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get feedDefaultHideReadPosts =>
      columnsByName['feed_default_hide_read_posts']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get feedActionBackToTop =>
      columnsByName['feed_action_back_to_top']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedActionCreateNew =>
      columnsByName['feed_action_create_new']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedActionExpandFab =>
      columnsByName['feed_action_expand_fab']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedActionRefresh =>
      columnsByName['feed_action_refresh']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedActionSetFilter =>
      columnsByName['feed_action_set_filter']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedActionSetSort =>
      columnsByName['feed_action_set_sort']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedActionSetView =>
      columnsByName['feed_action_set_view']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedActionHideReadPosts =>
      columnsByName['feed_action_hide_read_posts']!
          as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get enableSwipeActions =>
      columnsByName['enable_swipe_actions']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get swipeActionLeftShort =>
      columnsByName['swipe_action_left_short']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get swipeActionLeftLong =>
      columnsByName['swipe_action_left_long']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get swipeActionRightShort =>
      columnsByName['swipe_action_right_short']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get swipeActionRightLong =>
      columnsByName['swipe_action_right_long']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get swipeActionThreshold =>
      columnsByName['swipe_action_threshold']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get filterLists =>
      columnsByName['filter_lists']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get showErrors =>
      columnsByName['show_errors']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'auto_switch_account',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL REFERENCES accounts(handle)ON DELETE SET NULL',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'default_create_language',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'disable_tab_swiping',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (disable_tab_swiping IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ask_before_unsubscribing',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (ask_before_unsubscribing IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ask_before_deleting',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (ask_before_deleting IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'auto_play_videos',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (auto_play_videos IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'haptic_feedback',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (haptic_feedback IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'auto_translate',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (auto_translate IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'mark_threads_read_on_scroll',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (mark_threads_read_on_scroll IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'mark_microblogs_read_on_scroll',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NULL CHECK (mark_microblogs_read_on_scroll IN (0, 1))',
    );
i1.GeneratedColumn<double> _column_29(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'animation_speed',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'inline_replies',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (inline_replies IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'show_cross_post_comments',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (show_cross_post_comments IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'mark_cross_posts_as_read',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (mark_cross_posts_as_read IN (0, 1))',
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'default_image_store',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'app_language',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'theme_mode',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'color_scheme',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_37(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'enable_true_black',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (enable_true_black IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_38(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'compact_mode',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (compact_mode IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'hide_action_buttons',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (hide_action_buttons IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_40(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'hide_feed_u_i_on_scroll',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (hide_feed_u_i_on_scroll IN (0, 1))',
    );
i1.GeneratedColumn<double> _column_41(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'global_text_scale',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_42(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'always_show_instance',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (always_show_instance IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'cover_media_marked_sensitive',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (cover_media_marked_sensitive IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_44(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'full_image_size_threads',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (full_image_size_threads IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_45(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'full_image_size_microblogs',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (full_image_size_microblogs IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_46(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'show_posts_cards',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (show_posts_cards IN (0, 1))',
    );
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'post_component_order',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_48(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'divider_thickness',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'hide_emoji_reactions',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (hide_emoji_reactions IN (0, 1))',
    );
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'feed_view_order',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'feed_source_order',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'feed_sort_order',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'feed_default_threads_sort',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_54(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'feed_default_microblog_sort',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'feed_default_combined_sort',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_56(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'feed_default_explore_sort',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_57(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'feed_default_comment_sort',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_58(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'feed_default_hide_read_posts',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (feed_default_hide_read_posts IN (0, 1))',
    );
i1.GeneratedColumn<String> _column_59(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'feed_action_back_to_top',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_60(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'feed_action_create_new',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_61(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'feed_action_expand_fab',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_62(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'feed_action_refresh',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_63(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'feed_action_set_filter',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_64(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'feed_action_set_sort',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_65(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'feed_action_set_view',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_66(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'feed_action_hide_read_posts',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_67(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'enable_swipe_actions',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (enable_swipe_actions IN (0, 1))',
    );
i1.GeneratedColumn<String> _column_68(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'swipe_action_left_short',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_69(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'swipe_action_left_long',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_70(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'swipe_action_right_short',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_71(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'swipe_action_right_long',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_72(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'swipe_action_threshold',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_73(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'filter_lists',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_74(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'show_errors',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (show_errors IN (0, 1))',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_75(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get mainProfile =>
      columnsByName['main_profile']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get selectedProfile =>
      columnsByName['selected_profile']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get autoSelectProfile =>
      columnsByName['auto_select_profile']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get selectedAccount =>
      columnsByName['selected_account']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get webPushKeys =>
      columnsByName['web_push_keys']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get downloadsDir =>
      columnsByName['downloads_dir']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get expandNavDrawer =>
      columnsByName['expand_nav_drawer']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get expandNavStars =>
      columnsByName['expand_nav_stars']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get expandNavFeeds =>
      columnsByName['expand_nav_feeds']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get expandNavSubscriptions =>
      columnsByName['expand_nav_subscriptions']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get expandNavFollows =>
      columnsByName['expand_nav_follows']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get expandNavDomains =>
      columnsByName['expand_nav_domains']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_76(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (id = 1)',
    );
i1.GeneratedColumn<String> _column_77(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'main_profile',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES profiles(name)ON DELETE SET DEFAULT',
    );
i1.GeneratedColumn<String> _column_78(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'selected_profile',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES profiles(name)ON DELETE SET DEFAULT',
    );
i1.GeneratedColumn<String> _column_79(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'auto_select_profile',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL REFERENCES profiles(name)ON DELETE SET NULL',
    );
i1.GeneratedColumn<String> _column_80(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'selected_account',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES accounts(handle)ON DELETE SET DEFAULT',
    );
i1.GeneratedColumn<String> _column_81(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'web_push_keys',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_82(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'downloads_dir',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_83(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'expand_nav_drawer',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 1 CHECK (expand_nav_drawer IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_84(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'expand_nav_stars',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 1 CHECK (expand_nav_stars IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_85(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'expand_nav_feeds',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 1 CHECK (expand_nav_feeds IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_86(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'expand_nav_subscriptions',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 1 CHECK (expand_nav_subscriptions IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_87(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'expand_nav_follows',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 1 CHECK (expand_nav_follows IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_88(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'expand_nav_domains',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 1 CHECK (expand_nav_domains IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get body =>
      columnsByName['body']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get resourceId =>
      columnsByName['resource_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get at =>
      columnsByName['at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_89(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'body',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_90(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'resource_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_91(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT CURRENT_TIMESTAMP',
      defaultValue: const i1.CustomExpression('CURRENT_TIMESTAMP'),
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get tag =>
      columnsByName['tag']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get backgroundColor =>
      columnsByName['background_color']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get textColor =>
      columnsByName['text_color']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_92(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tag',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<int> _column_93(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'background_color',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_94(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'text_color',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get user =>
      columnsByName['user']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get tagId =>
      columnsByName['tag_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_95(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'user',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_96(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'tag_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES tags(id)ON DELETE CASCADE',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    accounts,
    feeds,
    feedInputs,
    servers,
    feedSourceCache,
    readPostCache,
    filterLists,
    profiles,
    stars,
    miscCache,
    drafts,
    tags,
    userTags,
    accountUnifiedpushToken,
  ];
  late final Shape13 accounts = Shape13(
    source: i0.VersionedTable(
      entityName: 'accounts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(handle)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_97,
        _column_98,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 feeds = Shape1(
    source: i0.VersionedTable(
      entityName: 'feeds',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(name)'],
      columns: [_column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 feedInputs = Shape2(
    source: i0.VersionedTable(
      entityName: 'feed_inputs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(name)'],
      columns: [_column_5, _column_4, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 servers = Shape3(
    source: i0.VersionedTable(
      entityName: 'servers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(name)'],
      columns: [_column_4, _column_7, _column_8],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 feedSourceCache = Shape4(
    source: i0.VersionedTable(
      entityName: 'feed_source_cache',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(name, server)'],
      columns: [_column_9, _column_10, _column_11, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 readPostCache = Shape5(
    source: i0.VersionedTable(
      entityName: 'read_post_cache',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(account, post_type, post_id)'],
      columns: [_column_12, _column_13, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 filterLists = Shape6(
    source: i0.VersionedTable(
      entityName: 'filter_lists',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(name)'],
      columns: [_column_4, _column_15, _column_16, _column_17, _column_18],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 profiles = Shape14(
    source: i0.VersionedTable(
      entityName: 'profiles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(name)'],
      columns: [
        _column_4,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_99,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
        _column_65,
        _column_66,
        _column_67,
        _column_68,
        _column_69,
        _column_70,
        _column_71,
        _column_72,
        _column_73,
        _column_74,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 stars = Shape8(
    source: i0.VersionedTable(
      entityName: 'stars',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_75, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 miscCache = Shape15(
    source: i0.VersionedTable(
      entityName: 'misc_cache',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_76,
        _column_77,
        _column_78,
        _column_79,
        _column_80,
        _column_81,
        _column_82,
        _column_83,
        _column_84,
        _column_85,
        _column_86,
        _column_87,
        _column_88,
        _column_100,
        _column_101,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 drafts = Shape10(
    source: i0.VersionedTable(
      entityName: 'drafts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_75, _column_89, _column_90, _column_91],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 tags = Shape11(
    source: i0.VersionedTable(
      entityName: 'tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_75, _column_92, _column_93, _column_94],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 userTags = Shape12(
    source: i0.VersionedTable(
      entityName: 'user_tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user, tag_id)'],
      columns: [_column_95, _column_96],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index accountUnifiedpushToken = i1.Index(
    'account_unifiedpushToken',
    'CREATE INDEX account_unifiedpushToken ON accounts (unifiedpush_token)',
  );
}

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get handle =>
      columnsByName['handle']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get oauth =>
      columnsByName['oauth']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get jwt =>
      columnsByName['jwt']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isPushRegistered =>
      columnsByName['is_push_registered']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get unifiedpushKey =>
      columnsByName['unifiedpush_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get unifiedpushToken =>
      columnsByName['unifiedpush_token']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_97(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'unifiedpush_key',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_98(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'unifiedpush_token',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get autoSwitchAccount =>
      columnsByName['auto_switch_account']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get defaultCreateLanguage =>
      columnsByName['default_create_language']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get disableTabSwiping =>
      columnsByName['disable_tab_swiping']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get askBeforeUnsubscribing =>
      columnsByName['ask_before_unsubscribing']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get askBeforeDeleting =>
      columnsByName['ask_before_deleting']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get autoPlayVideos =>
      columnsByName['auto_play_videos']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get hapticFeedback =>
      columnsByName['haptic_feedback']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get autoTranslate =>
      columnsByName['auto_translate']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get markThreadsReadOnScroll =>
      columnsByName['mark_threads_read_on_scroll']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get markMicroblogsReadOnScroll =>
      columnsByName['mark_microblogs_read_on_scroll']!
          as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get animationSpeed =>
      columnsByName['animation_speed']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get inlineReplies =>
      columnsByName['inline_replies']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get showCrossPostComments =>
      columnsByName['show_cross_post_comments']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get markCrossPostsAsRead =>
      columnsByName['mark_cross_posts_as_read']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get defaultImageStore =>
      columnsByName['default_image_store']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get defaultLinkAction =>
      columnsByName['default_link_action']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get appLanguage =>
      columnsByName['app_language']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get themeMode =>
      columnsByName['theme_mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get colorScheme =>
      columnsByName['color_scheme']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get enableTrueBlack =>
      columnsByName['enable_true_black']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get compactMode =>
      columnsByName['compact_mode']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get hideActionButtons =>
      columnsByName['hide_action_buttons']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get hideFeedUIOnScroll =>
      columnsByName['hide_feed_u_i_on_scroll']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get globalTextScale =>
      columnsByName['global_text_scale']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get alwaysShowInstance =>
      columnsByName['always_show_instance']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get coverMediaMarkedSensitive =>
      columnsByName['cover_media_marked_sensitive']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fullImageSizeThreads =>
      columnsByName['full_image_size_threads']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fullImageSizeMicroblogs =>
      columnsByName['full_image_size_microblogs']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get showPostsCards =>
      columnsByName['show_posts_cards']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get postComponentOrder =>
      columnsByName['post_component_order']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get dividerThickness =>
      columnsByName['divider_thickness']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get hideEmojiReactions =>
      columnsByName['hide_emoji_reactions']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get feedViewOrder =>
      columnsByName['feed_view_order']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedSourceOrder =>
      columnsByName['feed_source_order']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedSortOrder =>
      columnsByName['feed_sort_order']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedDefaultThreadsSort =>
      columnsByName['feed_default_threads_sort']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedDefaultMicroblogSort =>
      columnsByName['feed_default_microblog_sort']!
          as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedDefaultCombinedSort =>
      columnsByName['feed_default_combined_sort']!
          as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedDefaultExploreSort =>
      columnsByName['feed_default_explore_sort']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedDefaultCommentSort =>
      columnsByName['feed_default_comment_sort']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get feedDefaultHideReadPosts =>
      columnsByName['feed_default_hide_read_posts']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get feedActionBackToTop =>
      columnsByName['feed_action_back_to_top']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedActionCreateNew =>
      columnsByName['feed_action_create_new']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedActionExpandFab =>
      columnsByName['feed_action_expand_fab']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedActionRefresh =>
      columnsByName['feed_action_refresh']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedActionSetFilter =>
      columnsByName['feed_action_set_filter']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedActionSetSort =>
      columnsByName['feed_action_set_sort']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedActionSetView =>
      columnsByName['feed_action_set_view']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedActionHideReadPosts =>
      columnsByName['feed_action_hide_read_posts']!
          as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get enableSwipeActions =>
      columnsByName['enable_swipe_actions']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get swipeActionLeftShort =>
      columnsByName['swipe_action_left_short']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get swipeActionLeftLong =>
      columnsByName['swipe_action_left_long']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get swipeActionRightShort =>
      columnsByName['swipe_action_right_short']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get swipeActionRightLong =>
      columnsByName['swipe_action_right_long']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get swipeActionThreshold =>
      columnsByName['swipe_action_threshold']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get filterLists =>
      columnsByName['filter_lists']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get showErrors =>
      columnsByName['show_errors']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_99(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'default_link_action',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape15 extends i0.VersionedTable {
  Shape15({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get mainProfile =>
      columnsByName['main_profile']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get selectedProfile =>
      columnsByName['selected_profile']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get autoSelectProfile =>
      columnsByName['auto_select_profile']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get selectedAccount =>
      columnsByName['selected_account']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get webPushKeys =>
      columnsByName['web_push_keys']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get downloadsDir =>
      columnsByName['downloads_dir']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get expandNavDrawer =>
      columnsByName['expand_nav_drawer']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get expandNavStars =>
      columnsByName['expand_nav_stars']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get expandNavFeeds =>
      columnsByName['expand_nav_feeds']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get expandNavSubscriptions =>
      columnsByName['expand_nav_subscriptions']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get expandNavFollows =>
      columnsByName['expand_nav_follows']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get expandNavDomains =>
      columnsByName['expand_nav_domains']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get unifiedpushDistributorName =>
      columnsByName['unifiedpush_distributor_name']!
          as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get unifiedpushDistributorAck =>
      columnsByName['unifiedpush_distributor_ack']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_100(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'unifiedpush_distributor_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_101(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'unifiedpush_distributor_ack',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (unifiedpush_distributor_ack IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2, from2To3: from2To3),
);
