include: package:very_good_analysis/analysis_options.yaml

formatter:
  # Keep formatting consistent by automating trailing commas.
  trailing_commas: automate

analyzer:
  errors:
    # Needed for build runner annotations (i.e., freezed, json_serializable).
    invalid_annotation_target: ignore
    # We don't need to document every single public member.
    public_member_api_docs: ignore
